name: "Lifting tools CXX-Common"
description: "Build cxx-common latest for lifting-tools"
inputs:
  target-export-path: # id of input
    description: "where to export the cxx-common build"
    required: true
  gh-token:
    description: "token for the target nuget cache"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        repository: "https://github.com/lifting-bits/cxx-common.git"
    - name: "Bootstrap vcpkg"
      shell: "bash"
      run: |
        ./vcpkg/bootstrap-vcpkg.sh
    - name: "Setup NuGet Credentials"
      shell: "bash"
      # Replace <OWNER> with your organization name
      run: |
        mono `./vcpkg/vcpkg fetch nuget | tail -n 1` \
          sources add \
          -source "https://nuget.pkg.github.com/lifting-bits/index.json" \
          -storepasswordincleartext \
          -name "GitHub" \
          -username "lifting-bits" \
          -password "${{ inputs.gh-token }}"
        mono `./vcpkg/vcpkg fetch nuget | tail -n 1` \
          setapikey "${{ inputs.gh-token }}" \
          -source "https://nuget.pkg.github.com/lifting-bits/index.json"
    # Omit this step if you're using manifests
    - name: "vcpkg package restore"
      shell: "bash"
      run: >
        ./vcpkg/vcpkg install sqlite3 cpprestsdk
    - run: ./build_dependencies.sh --release --export-dir ${{ inputs.target-export-path }} ${{ matrix.llvm }} --debug
      shell: bash
