name: "Lifting tools CXX-Common"
description: "Build cxx-common latest for lifting-tools"
inputs:
  target-export-path: # id of input
    description: "where to export the cxx-common build"
    required: true
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        repository: "https://github.com/lifting-bits/cxx-common.git"
    - name: "Bootstrap vcpkg"
      shell: "bash"
      run: |
        ./vcpkg/bootstrap-vcpkg.sh
    - name: "Setup NuGet Credentials"
      shell: "bash"
      # Replace <OWNER> with your organization name
      run: |
        mono `./vcpkg/vcpkg fetch nuget | tail -n 1` \
          sources add \
          -source "https://nuget.pkg.github.com/<OWNER>/index.json" \
          -storepasswordincleartext \
          -name "GitHub" \
          -username "lifting-bits" \
          -password "${{ secrets.GITHUB_TOKEN }}"
        mono `./vcpkg/vcpkg fetch nuget | tail -n 1` \
          setapikey "${{ secrets.GITHUB_TOKEN }}" \
          -source "https://nuget.pkg.github.com/<OWNER>/index.json"
    # Omit this step if you're using manifests
    - name: "vcpkg package restore"
      shell: "bash"
      run: >
        ./vcpkg/vcpkg install sqlite3 cpprestsdk
    - run: ./build_dependencies.sh --release --export-dir ./${{ env.ARTIFACT_NAME }} ${{ matrix.llvm }} --clean-after-build --debug
      shell: bash
